name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
# name: Test
#
# on: [push, pull_request]
#
# env: 
#   CARGO_TERM_COLOR: always
#   NOTMUCH_CONFIG: notmuch-testconfig
#
# jobs:
#     test:
#         name: nm-livesearcher
#         runs-on: ubuntu-22.04
#         steps:
#             - uses: actions/checkout@v3
#             - name: Setup
#               run: |
#                   sudo apt-get update
#                   sudo apt-get install notmuch
#                   sudo apt-get install libnotmuch-dev
#             - uses: actions/checkout@v2
#               with:
#                 repository: dagle/galore-test
#                 path: test
#             - name: Test
#                 # - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
#                 run: |
#                   rustup update 
#                   cargo build --verbose
#                   cargo test --verbose
